export const productos = [
  {
    id: 1,
    imagenes: "/paquete_medicamentos.png, /paquete_medicamentos.png, /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    nombre: "Paquete Medicamentos",
    contenido: "Analgésicos (paracetamol e ibuprofeno), Antiséptico para heridas, Bandas adhesivas (curitas), Jarabe para la tos",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    categoria: "Salud y Belleza",
    precio: 1990,
    stock: 10,
    fecha: "23/01/2024",
  },
  {
    id: 2,
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    nombre: "Paquete Cuidado Facial",
    contenido: "Limpiador facial, Tónico, Hidratante, Protector solar",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    categoria: "Salud y Belleza",
    precio: 45099,
    stock: 5,
    fecha: "7/04/2024",
  },
  {
    id: 3,
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    categoria: "Alimentos",
    nombre: "Paquete Almuerzo Rápido",
    contenido: "Wraps de pollo y vegetales, Fruta fresca (manzanas y naranjas), Botellas de agua mineral, Barras de granola",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 9670,
    stock: 20,
    fecha: "15/09/2024",
  },
  {
    id: 4,
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    nombre: "Paquete Noche de Películas",
    contenido: "Palomitas de maíz, Chocolates y dulces, Snacks salados (papas fritas, nachos)",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    categoria: "Alimentos",
    precio: 21700,
    stock: 8,
    fecha: "12/04/2024",
  },
  {
    id: 5,
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    nombre: "Paquete Perro Feliz",
    categoria: "Mascotas",
    contenido: "Comida premium para perros, Juguetes masticables, Premios para perros, Shampoo para perros",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 8990,
    stock: 15,
    fecha: "5/04/2024",
  },
  {
    id: 6,
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    categoria: "Mascotas",
    nombre: "Paquete Gato Consentido",
    contenido: "Arena para gatos, Juguetes interactivos, Snacks para gatos",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 1820,
    stock: 25,
    fecha: "1/06/2024",
  },
  {
    id: 7,
    categoria: "Oficina",
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    nombre: "Paquete Oficina en Casa",
    contenido: "Cuadernos y bolígrafos, Café premium y tazas, Snacks saludables (frutos secos y barras de proteína), Auriculares con micrófono",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 1425,
    stock: 30,
    fecha: "13/02/2024",
  },
  {
    id: 8,
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png", 
    categoria: "Oficina",
    nombre: "Paquete Oficina Organizada",
    contenido: "Organizadores de escritorio, Soporte para laptop, Calendario y planificador semanal, Grapadora y grapas",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 7600,
    stock: 12,
    fecha: "31/01/2024",
  },
  {
    id: 9,
    categoria: "Alimentos",
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    nombre: "Paquete dulce",
    contenido: "Barra de Kitkat, Ositos Mogul",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 1535,
    stock: 20,
    fecha: "30/08/2024",
  },
  {
    id: 10,
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    categoria: "Ocio",
    nombre: "Paquete Previa",
    contenido: "10 Latas Guiness Stout, Maní",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 9900,
    stock: 10,
    fecha: "15/03/2024",
  },
  {
    id: 11,
    categoria: "Alimentos",
    imagenes:"/paquete_facial.png, /paquete_medicamentos.png,  /paquete_almuerzo.png, /paquete_noche_peliculas.png",
    nombre: "Paquete Salado",
    contenido: "Doritos Sabor Queso, Papitas Lays Sabor Asado",
    caracteristicas: [
      "Alimentos",
      "Higiene",
      "Diversion",
      "Mascotas",
      "Perros",
    ],
    precio: 3100,
    stock: 50,
    fecha: "26/11/2024",
  },
];

export const arrayToLowerCase = (arr) => {
  return arr.map((str) => str.toLowerCase());
};
