export const productos = [
  {
    id: 1,
    imagen: "/paquete_medicamentos.png",
    nombre: "Paquete Medicamentos",
    contenido: [
      "Analgésicos (paracetamol, ibuprofeno)",
      "Antiséptico para heridas",
      "Bandas adhesivas (curitas)",
      "Jarabe para la tos",
    ],
    categoria: "Salud y Belleza",
    precio: 1990,
    stock: 10,
  },
  {
    id: 2,
    imagen: "/paquete_facial.png",
    nombre: "Paquete Cuidado Facial",
    contenido: ["Limpiador facial", "Tónico", "Hidratante", "Protector solar"],
    categoria: "Salud y Belleza",
    precio: 45099,
    stock: 5,
  },
  {
    id: 3,
    imagen: "/paquete_almuerzo.png",
    categoria: "Alimentos",
    nombre: "Paquete Almuerzo Rápido",
    contenido: [
      "Wraps de pollo y vegetales",
      "Fruta fresca (manzanas, naranjas)",
      "Botellas de agua mineral",
      "Barras de granola",
    ],
    precio: 9670,
    stock: 20,
  },
  {
    id: 4,
    imagen: "/paquete_noche_peliculas.png",
    nombre: "Paquete Noche de Películas",
    contenido: [
      "Palomitas de maíz",
      "Chocolates y dulces",
      "Snacks salados (papas fritas, nachos)",
    ],
    categoria: "Alimentos",
    precio: 21700,
    stock: 8,
  },
  {
    id: 5,
    imagen: "/paquete_perro.png",
    nombre: "Paquete Perro Feliz",
    categoria: "Mascotas",
    contenido: [
      "Comida premium para perros",
      "Juguetes masticables",
      "Premios para perros",
      "Shampoo para perros",
    ],
    precio: 8990,
    stock: 15,
  },
  {
    id: 6,
    imagen: "/paquete_gato.png",
    categoria: "Mascotas",
    nombre: "Paquete Gato Consentido",
    contenido: [
      "Arena para gatos",
      "Juguetes interactivos",
      "Snacks para gatos",
    ],
    precio: 1820,
    stock: 25,
  },
  {
    id: 7,
    categoria: "Oficina",
    imagen: "/paquete_oficina_casa.png",
    nombre: "Paquete Oficina en Casa",
    contenido: [
      "Cuadernos y bolígrafos",
      "Café premium y tazas",
      "Snacks saludables (frutos secos, barras de proteína)",
      "Auriculares con micrófono",
    ],
    precio: 1425,
    stock: 30,
  },
  {
    id: 8,
    imagen: "/paquete_oficina_organizada.png",
    categoria: "Oficina",
    nombre: "Paquete Oficina Organizada",
    contenido: [
      "Organizadores de escritorio",
      "Soporte para laptop",
      "Calendario y planificador semanal",
      "Grapadora y grapas",
    ],
    precio: 7600,
    stock: 12,
  },
  {
    id: 9,
    categoria: "Alimentos",
    imagen: "/paquete_dulce.png",
    nombre: "Paquete dulce",
    contenido: ["Barra de Kitkat", "Ositos Mogul"],
    precio: 1535,
    stock: 20,
  },
  {
    id: 10,
    imagen: "/paquete_previa.png",
    categoria: "Ocio",
    nombre: "Paquete Previa",
    contenido: ["10 Latas Guiness Stout", "Maní"],
    precio: 9900,
    stock: 10,
  },
  {
    id: 11,
    categoria: "Alimentos",
    imagen:
      "https://raw.githubusercontent.com/MateoPane/SupermercadoParcial/main/imgs/doritos.png",
    nombre: "Paquete Salado",
    contenido: ["Doritos Sabor Queso", "Papitas Lays Sabor Asado"],
    precio: 3100,
    stock: 50,
  },
];
